### ISSUE TITLE
Revisión modelo de la base de datos

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/resoluciones_docentes_crud#1]
Revisar y desplegar el modelo de la base de datos y contrastarlo con los lineamientos definidos por la OAS para su aprobación por parte de arquitectura y dba.

- [x] Modificar` el esquema de datos de acuerdo a los lineamientos.
- [x] Generar el script para correr la nueva base de datos.
- [x] Probar la base de datos en local.
- [x] Desplegar la base de datos al ambiente de pruebas.
- [x] Migrar la base de datos.

Esta tarjeta viene con la misma información del siguiente issue asignada al nuevo repositorio de resoluciones_crud: https://github.com/udistrital/resoluciones_cliente/issues/69

**Comment by anndresfelipe29** [comment]
Con el analisis de inicio se encuentra documentado el siguiente esquema para el aplicativo de resoluciones:
![image](https://user-images.githubusercontent.com/30865375/105205131-e7b6fc00-5b12-11eb-946c-80f6235e35bc.png)

**Comment by anndresfelipe29** [comment]
Se aplican correcciones al esquema existente a partir de las tablas que se encuentran en preproduccion y los lineamientos obteniendo :
![image](https://user-images.githubusercontent.com/30865375/105205228-01f0da00-5b13-11eb-9ac6-fd32467f63ee.png)

Se solicita revision por parte de @corio27 y de los dba @fnrojash , @blacburn y @nodier25

**Comment by anndresfelipe29** [comment]
![image](https://user-images.githubusercontent.com/30865375/105205288-18973100-5b13-11eb-9b1c-84340326689c.png)

**Comment by anndresfelipe29** [comment]
Se hacen los ajustes mencionados por @blacburn obteniendo:
![resoluciones2](https://user-images.githubusercontent.com/30865375/105205561-64e27100-5b13-11eb-81bb-d22d2c4a3685.png)

Se solicita revision por parte de @corio27 y de los dba @fnrojash , @blacburn y @nodier25

**Comment by blacburn** [comment]
Buen día, 

Por parte del equipo DBA, se valida el modelo en su última versión , se indica que se han aplicado los cambios indicados, por lo cual se aprueba el modelo expuesto.

Gracias.
