### ISSUE TITLE
Ampliar filtro para consultar las resoluciones a las que se encuentra vinculado el docente.

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/resoluciones_docentes_crud#10]
Se requiere que el usuario pueda filtrar no solo por el numero de documento del docente, por ende se debe ampliar el filtro para que este tenga las siguientes 2 opciones extra de filtro:
- [x] Vigencia de Resolucion
- [x] Periodo de Carga.

---

Recomendaciones:
- si es posible tener un input o select con auto-completado, de no ser posible se sugieren las 2 siguientes opciones:
  - input con un ejemplo en el placeholder o Tooltip.
  - Select con las opciones disponibles.
- para mostrar los recomienda una tabla (en caso de que esta aun no este implementada).

**Comment by jupmorenor** [comment]
Este requerimiento fué desarrollado en conjunto en udistrital/resoluciones_mid_v2#10, específicamente en el commit udistrital/resoluciones_mid_v2@2873987
