### ISSUE TITLE
Elección múltiple de CDP

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/resoluciones_docentes_crud#12]
A la hora de vincular a un docente poder escoger diferentes CDP para los distintos rubros presupuestales.

**Comment by jupmorenor** [comment]
Desarrollado en https://github.com/udistrital/resoluciones_cliente_v2/issues/11, específicamente en el commit https://github.com/udistrital/resoluciones_cliente_v2/commit/2a214898da24a15e4a8c9778f1c3f39e6a03d8dd
