### ISSUE TITLE
Elaboración de ETL para migración de datos

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_docentes_crud#16]
Como sugerencia de los DBAs, se debe realizar la creación de un ETL (Extract, transform and load) para que la migración de datos en producción, pasando de una BD a otra se haga de forma automática y no se mitiguen posibles problemas.

**Criterio de aceptación**

- [x] Formulación de ETL sujeta a validación por parte del equipo de DBAs.

**Nota**: en caso de ser necesario, se contará con el apoyo de los DBAs encargados.

**Comment by jupmorenor** [comment]
Se generó proyecto en Talend para migración de datos por medio de un ETL desde la base de datos **udistrital_core_db**, esquema **administrativa** hacia la base de datos **udistrital_administrativa**, esquema **resoluciones**

![Resoluciones ETL](https://user-images.githubusercontent.com/11802554/130674053-5d334a75-d48e-48fd-9a5f-344122180c64.png)

https://drive.google.com/file/d/1-20zNTgot5-L9z255zu-HQd1k67NcTKp/view?usp=sharing

**Comment by jupmorenor** [comment]
Para la ejecución del ETL es necesario primero crear el esquema de datos en la base de datos destino ejecutando los scripts de las migrations asi: [script_1](https://github.com/udistrital/resoluciones_docentes_crud/blob/release/0.0.1/database/scripts/20210120_153032_crear_esquema_resoluciones_bd_up.sql) y [script_2](https://github.com/udistrital/resoluciones_docentes_crud/blob/release/0.0.1/database/scripts/20210924_145046_cuadro_responsabilidad_up.sql)
Los datos de las tablas paramétricas se transfieren a través del ETL para conservar su integridad.

En el ETL es necesario configurar las conexiones a las bases de datos de origen y destino con las credenciales correspondientes para poder ejecutarlo.

~~Al finalizar la ejecución del ETL se debe aplicar un script sql sobre la base de datos para que se actualicen las secuencias de las llaves primarias del esquema y evitar errores por duplicidad cuando se comience a insertar datos. [link al script](https://drive.google.com/file/d/1a1-onepVmGV6SSqO_lQH9uMano6xb2h0/view?usp=sharing)~~

**Comment by jupmorenor** [comment]
Se actualiza el ETL adjuntando al final un componente que ejecuta el script que actualiza las secuencias
