### ISSUE TITLE
Creación del api crud para el sistema de resoluciones

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/resoluciones_docentes_crud#3]
Creación del api crud siguiendo los lineamientos suministrados por la OAS. 

https://github.com/udistrital/lineamientos_oas#5-apis-beego-mortar_board

- [x] Crear la aplicación beego para la base de datos
- [x] Dockerizar la aplicación CRUD
- [x] Realizar el refactor de la aplicación
- [x] Probar de manera manual el funcionamiento del CRUD realizado
- [x] Crear la aplicación beego para la base de datos del hito anterior.
- [x] Dockerizar la aplicación CRUD.
- [x] Migrar las clases contenido_resolucion y resolucion_vinculacion al nuevo CRUD. ajustes 
- [x] Realizar el refactor de la aplicación.
- [x] Probar de manera manual el funcionamiento del CRUD realizado. siguiente
- [x] Realizar pruebas con GoDog al CRUD. siguiente 
- [x] Desplegar en pruebas el CRUD. 4 de febrero
- [x] Registrar CRUD en WSO2. siguiente

**Comment by anndresfelipe29** [comment]
Se crea el nuevo crud con:
- El siguiente esquema de base de datos:
![image](https://user-images.githubusercontent.com/30865375/106494077-f775ff00-6487-11eb-990f-6895b61134e3.png)
- Se dockeriza la aplicación:
![image](https://user-images.githubusercontent.com/30865375/106494184-1c6a7200-6488-11eb-90a8-b5d7399a3573.png)
- Se migran los controladores necesarios para el funcionamiento de resoluciones desde administrativa crud (Resolución vinculacion y contenido resolucion).
- Se aplica refactor a todo el proyecto de acuerdo al lineamiento de la OAS y se aplica el nuevo refactor a las clases migradas de administrativa crud.
![image](https://user-images.githubusercontent.com/30865375/106494750-cd710c80-6488-11eb-95fe-e26a68242cfa.png)
![image](https://user-images.githubusercontent.com/30865375/106494783-d9f56500-6488-11eb-88c3-6c23618163ff.png)
- Se obtiene la siguiente estructura para el proyecto:
![image](https://user-images.githubusercontent.com/30865375/106494850-ee396200-6488-11eb-991c-0a5a61f1035a.png)
- Se realizan 2 migraciones, una para la creación del esquema de base de datos y otro para poblar las tablas parametricas del esquema:
![image](https://user-images.githubusercontent.com/30865375/106494996-1c1ea680-6489-11eb-8136-3963fed328ca.png)
