### ISSUE TITLE
Creación de pruebas unitarias api crud

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/resoluciones_docentes_crud#4]
Realizar las pruebas unitarias para el api crud según los lineamientos suministrados por la OAS

https://github.com/udistrital/lineamientos_oas#51-pruebas-unitarias-api-beego-mag

**Comment by ddguerra90** [comment]
Generación del CRUD Resoluciones:

- [ ] Crear la aplicación beego para la base de datos del hito anterior.
- [ ] Dockerizar la aplicación CRUD.
- [ ] Migrar las clases contenido_resolucion y resolucion_vinculacion al nuevo CRUD. ajustes 
- [ ] Realizar el refactor de la aplicación.
- [ ] Probar de manera manual el funcionamiento del CRUD realizado. siguiente
- [ ] Realizar pruebas con GoDog al CRUD. siguiente 
- [ ] Desplegar en pruebas el CRUD. 4 de febrero
- [ ] Registrar CRUD en WSO2. siguiente

**Comment by diagutierrezro** [comment]
Se realizan las pruebas unitarias de los controladores del nuevo crud de resoluciones las cuales se le hacen a los controladores usando goconvey de la siguiente manera 
![image](https://user-images.githubusercontent.com/38676533/110990934-fca95200-8341-11eb-928e-432dd5b6f92f.png)
Estas pruebas fueron mostradas a José Javier Vargas el cual dijo que no había necesidad de realizarlas a los modelos por lo que únicamente se dejan en los controladores.
