### ISSUE TITLE
Perfeccionar servicio que consulta saldo de un CDP

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/resoluciones_docentes_crud#8]
El servicio que permite consultar el saldo de un CDP, debe perfeccionarse, puesto que resoluciones lo consulta, pero los datos no son acordes.

**Objetivos**
(en el cliente)

 revisar función de solicitud de CDP.
 realizar pruebas para encontrar incoherencias o errores.
 en el presente commit listar las inconsistencia s encontradas.
 solución de incoherencias.
(en caso de ser lio del api informarlo en el presente issue y realizar los 4 objetivos anteriormente mencionados)

**Comment by jupmorenor** [comment]
ver https://github.com/udistrital/resoluciones_cliente/issues/16
