### ISSUE TITLE
Servicio de mostrar el desagregado del valor del contrato en los diferentes rubros presupuestales.

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/resoluciones_docentes_crud#9]
En la anterior fase uno de los requerimientos era mostrar el valor total del contrato de forma desagregada es los diferentes rubros presupuestales ya definidos. Se logro mostrar dicha información pero al final el usuario propuso que la tabla se redujera y la única forma era mostrarla con mas columnas y no filas. Para ello se pensó en su momento expedir las resoluciones en formatos horizontales. Para abordar esta tarea primero que todo se debe definir si autoriza la dependencia encargada a que las resoluciones se muestren de esa manera.

A continuación se mencionan los issues en los cuales se trabajo en el desarrollo de la funcionalidad para la desagregación.

https://github.com/udistrital/resoluciones_cliente/issues/55

https://github.com/udistrital/resoluciones_cliente/issues/11

En reunión con la Jefe Beatriz se definió que se va ajustar el actual reporte que se puede expedir en resoluciones y mostrar allí el desagregado del salario total del docente según los rubros presupuestales definidos.

**Comment by jupmorenor** [comment]
Se continua en el issue mencionado.
